test: add test for import attributes
nodejs/import-in-the-middle pull request #74
Opened 2024-05-06 11:59 UTC by chentsulin

Add a test for import attributes on Node 19+.

2024-05-06 14:28 UTC, Qard approved these changes

2024-05-31 13:10 UTC, bengl approved these changes

2024-05-31 13:12 UTC, bengl commented
@chentsulin The acorn parser seems to be erroring out on tests on the 20.x builds. Can you take a look at that please?

2024-05-31 13:12 UTC, bengl requested changes
Test failures need to be fixed.

2025-05-08 19:35 UTC, timfish commented
I'm going to close this PR to try and reduce how many old ones we have open!

I think we support import attributes now!

2025-05-08 19:35 UTC, closed without merging